runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.app

- url: (.*)/
  static_files: index.html
  upload: index.html

- url: /app
  static_dir: app

- url: /assets
  static_dir: assets